### PR TITLE
python2 and python3 versions, use ubuntu 16.04

### PR DESCRIPTION
**Pull request by mehanig**
Hi, I used https://github.com/dockerfiles/django-uwsgi-nginx/pull/14 as a reference to keep both versions.

Don't know if author planning to update it.

I updated both Dockerfiles, python2 docker file is different from 14.04 file in line `apt get install python-pip` , seems like that's correct way in 16.04 to install pip, instead of `easy_install pip`

I also updated Readme and mapped ports from container to host, seems like it would be easier to detect if container builded and started without problem on.

### CODE REVIEW

**Comment by vartagg** [comment]
+1 very useful.

**Comment by mehanig** [comment]
@dhrp Could you pls review?

**Comment by jonesnc** [comment]
I'd also like to see these changes merged.

**Comment by dhrp** [comment]
Thanks guys! And sorry for the slow reply, I have been travelling.

**Pull request merged**
